version: '3'
services:
  web:
    image: takoyaki0316/puppeteer
    build: .
    environment:
      - PORT
    working_dir: /app
    command: npm start
    ports:
      - $PORT
    networks:
      - traefik-public
    deploy:
      replicas: ${REPLICAS}
      labels:
        - traefik.frontend.rule=Host:developers.${DOMAIN?Variable DOMAIN not set};Path:/ogpup
        - traefik.port=${PORT}
        - traefik.backend=ogpup
        - traefik.docker.network=traefik-public
        - traefik.tags=traefik-public
        - traefik.enable=true
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
networks:
  traefik-public:
    external: true
