version: '3'
services:
  web:
    image: takoyaki0316/puppeteer
    build: .
    environment:
      - PORT
    working_dir: /app
    command: npm start
    volumes:
      - .:/app
    ports:
      - $PORT
    networks:
      - traefik-public
    deploy:
      replicas: 2
      labels:
        - traefik.frontend.rule=Host:${DOMAIN?Variable DOMAIN not set}
        - traefik.port=${PORT}
        - traefik.backend=puppeteer
        - traefik.docker.network=traefik-public
        - traefik.tags=traefik-public
        - traefik.enable=true
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
networks:
  traefik-public:
    external: true
