version: '3'
services:
  web:
    image: takoyaki0316/puppeteer
    container_name: "puppeteer-thumbnail"
    environment:
      - VIRTUAL_HOST=wooooo.cf
      - PORT
    deploy:
      replicas: 2  
    working_dir: /app
    command: npm start
    volumes:
      - .:/app
    ports:
      - $PORT

networks:
  default:
    external:
      name: shared
